const whiteCardDeck = [
  "forcing Lucien to watch as his lover is executed",
  "using the cauldron to destroy the wall",
  "slamming your mental walls down",
  "buying your little sister paint with the little money you have",
  "'Don't put the books together.' *Feyre proceeds to put the books together",
  "Lucien makes a triumphant but terribly late return",
  "trying to cross the wall after Feyre got kidnapped",
  "'Hello, Feyre darling.'",
  "'Thank the Cauldron'",
  "High Lady of the Night Court",
  "Ianthe's righteous death",
  "the darkness staring back",
  "a messenger and soldier-assassin for a wrathful god who ruled a young world",
  "trolling Ianthe",
  "The Children of the Blessed",
  "Gwyn",
  "a vulgar gesture",
  "the attor",
  "boning in the sky",
  "scenting arousal",
  "Chapter 55",
  "Starfall",
  "The Dread Trove",
  "the mental image of Tamlin groveling at Rhysand's feet",
  "cutting a ribbon",
  "hissing",
  "The unhinged subgroup of ACOTAR fans who are still on Team Tamlin",
  "'Cauldron Boil Me'",
  "the prison",
  "Tamlin sitting alone with a dead elk",
  "exclusively picturing the Middengard Wyrm as the Alaskan Bullworm from Spongebob",
  "letting all of Prythian think you're a terrible person who rules over a terrible court",
  "telling Rhys you want peace then immediately turning around and telling Hybern about Velaris",
  "The Morrigan",
  "Nesta",
  "keeping the existence of an entire city a secret",
  "female characters always losing their super cool powers",
  "'Lest you forget where this is going to end.'",
  "The human queens betrayed you? What a surprise!",
  "being one-quarter nymph",
  "Nesta sacrificing herself to save Feyre and Rhys",
  "'Nesta doesn't want to come to anything ever.'",
  "Feyre's starfall dress",
  "spilling lentils in a fireplace",
  "the scene at the inn",
  "Elain being a badass and stabbing Hybern with truth teller",
  "strategically turning everyone against Tamlin",
  "killing the attor in the most badass way imaginable",
  "Azriel's failure as a babysitter",
  "The Night Court",
  "throwing a shoe at the High Lord of the Night Court",
  "Velaris",
  "Tamlin's Talons",
  "casually keeping a pet Middengard Wyrm",
  "Rhysand's naked nightmare",
  "falling in love with Feyre because she reminds you of Cassian?!",
  "gouging out Lucien's eye",
  "the power of 'pure death'",
  "Feyre's weird creature alter ego she saw in the Ourboros mirror",
  "wearing a human's eyeball as a statement ring",
  "Cassian's seed",
  "Nesta leaving the goddamn tree",
  "the monster trapped in a beautiful body",
  "Lucien's missing eye",
  "Alis",
  "telling Feyre the truth about her doomed pregnancy",
  "Tamlin's jerkin",
  "going for a swim in the cauldron",
  "the splattered remains of the attor",
  "'Be careful how you speak about my High Lady.'",
  "Feyre's dad getting his knee absolutely obliterated by 'thugs.'",
  "Cresseida",
  "mist and fury",
  "giving the most vague and misleading advice imaginable",
  "drugging Feyre every night for months",
  "The House of Wind",
  "Cursebreaker",
  "Inner Peace",
  "considerable length",
  "a preference for lamb's blood",
  "the blight",
  "owing Nesta one favor",
  "exhausting your powers the night before battle by winnowing the entirety of the human realm",
  "Not a shadow. An Illyrian warrior.",
  "bribing the Suriel with a chicken",
  "the Elucien stans",
  "pining for Grayson",
  "The City of Starlight",
  "Elain's bread",
  "trying to figure out what Mor's power is",
  "falling in love with Azriel even though he only spoke like 5 words in the entire series",
  "being illiterate",
  "wearing dresses made by your mate's dead mom",
  "plucking out Demetra's eyeballs",
  "giving lamb's blood as a gift",
  "winnowing",
  "recommending ACOTAR to everyone you know and then regretting it once you remember it's fairy porn",
  "feeling Cassian's balls slap against your thighs",
  "having a heart of stone",
  "Rhys kind of being a dick when written from anyone's perspective but Feyre's",
  "regifting a necklace",
  "sending Rhys his mother's and sister's heads in a box",
  "impaling Demetra on a lamppost",
  "receiving ANOTHER painting from Feyre and pretending to be excited about it",
  "hiding behind a curtain when Rhysand comes to visit",
  "not being able to read",
  "destroying the lives of innocent people in the Spring Court just to get back at your ex-fiance",
  "Rhys trying to ignore the fact that his mate is about to marry his enemy",
  "thorns and roses",
  "a tendril of power",
  "The Wild Hunt",
  "the Spymaster",
  "Nesta and her signature 'death promise point' move",
  "that sad little blue lesser fairy who lost his wings to Amarantha",
  "Helion's bisexual tendencies",
  "the Veritas Orb",
  "leaving Nesta in a tree",
  "the water wraiths",
  "badass librarians",
  "skinny dipping in the pool of starlight",
  "having a spiritual awakening hearing a bunch of librarians/priestesses sing",
  "settling a debt ;)",
  "daemati",
  "being the sole provider for your family at the ripe age of fourteen",
  "knowing Feyre's family would last maybe 2 days without her",
  "The Suriel",
  "smelling of citrus and the sea",
  "nonchalantly eating dinner with Azriel at the dining room table after getting a blow job",
  "Lucien just casually hiding the fact that he could see past glamours",
  "Emerie's asshole cousin Bellius",
  "accidentally opening all of the doors of the prison",
  "sending Feyre back wearing night court fashion",
  "The Winter Court",
  "Feyre",
  "Rhysand's knee tattoo",
  "cursing an entire kingdon just because you couldn't get with Tamlin",
  "breasts becoming 'heavy'",
  "Bryaxis",
  "being controlled by the crown",
  "going on a soul searching hike with Cassian",
  "a tramp stamp bargain tattoo",
  "Feyre's stick figure paintings",
  "convincing Eris to propose after just one dance",
  "the entire concept of Calanmai is really fucking weird",
  "a house that likes to read smut",
  "sending music into Feyre's cell instead of just helping her in any useful way",
  "racking up a massive bill for Rhysand to pay",
  "completely uprooting your entire life because you killed a wolf",
  "Rhys creating the bargain with Feyre just to piss off Tamlin",
  "The Spring Court",
  "death on swift wings",
  "resurrecting Miryam",
  "depressed Tamlin aimlessly running around the Spring Court in his beast form",
  "Cassian's dance lessons",
  "'There you are, I've been looking for you.'",
  "Thesan",
  "defending your art gallery with a bit of rusted pipe",
  "dropping cryptic predictions about Cassian's death",
  "Eris",
  "Cassian",
  "causing an avalanche as you climax",
  "sacrificing yourself to repair the cauldron",
  "Gwynriel stans",
  "staying strapped at all times with an ash arrow",
  "Rhys checking every corpse on the battlefield searching for Cassian",
  "thinking that climbing up the stairs would be easier than going down the stairs",
  "dissent among the Illyrians",
  "getting your wings clipped",
  "getting abducted by fae",
  "letting Feyre get abducted by a terrible fae beast",
  "feeling darkness beckoning while on the 7th floor of the library",
  "spending your days carving wood instead of providing for your impoverished family",
  "sleeping blissfully next to your traumatized fiance",
  "Jurian's eye",
  "the bat boys",
  "the apex of my thighs",
  "Calanmai",
  "snapping Feyre's neck",
  "accidentally making a cursed sword",
  "Daddy Azriel",
  "wing play",
  "Ataraxia",
  "being able to repair Cassian's exposed intestines but not being able to perform a C-section",
  "buying Feyre a house for Solstice",
  "the mental image of Lucien flying with Azriel",
  "keeping Feyre's impending death a secret from her",
  "Water Wolves",
  "the bog of Oorid",
  "Helion",
  "Viviane wanting to be a High Lady too",
  "dating someone 500 years younger than you",
  "kneeing Cassian in the nuts",
  "Gwyn's singing",
  "'My right knee gets a twinge of pain when it rains.'",
  "Tamlin",
  "Ressina",
  "blocking out the fact they're all wearing masks for the entirety of the first book",
  "getting drunk on fairy wine",
  "Evil Elain",
  "'Like calls to like.'",
  "butchering dozens of Winter Court children",
  "siphons",
  "impatiently waiting for the next ACOTAR book",
  "friendship bracelets",
  "receiving a blood ruby from the Summer Court",
  "the blood rite",
  "nailing a note to Mor's womb",
  "Jurian",
  "leathery wings",
  "Beron",
  "flying lessons with Azriel",
  "Amren's puzzle hobby",
  "Emerie",
  "the High Lord's meeting",
  "Feyre barely using her badass powers at the final battle for some reason",
  "spending 50 years under the mountain",
  "shaking the mountains every time you orgasm",
  "Azriel",
  "showing up to Hybern at the last possible moment",
  "Tamlin playing the fiddle",
  "getting fingered in public",
  "stabbling Tamlin",
  "'the forest had become a labyrinth of snow and ice.'",
  "Cassian and Azriel slamming into the ice",
  "The Weaver",
  "convincing anyone reading ACOTAR for the first time that you too adore Tamlin",
  "being Amarantha's whore",
  "tossing your gift into the Sidra",
  "Hybern",
  "dripping silent tears into your scrambled eggs",
  "theatrically pretending to break the mating bond",
  "those little wood carvings Feyre's dad made",
  "the Reesand vs. Ricesand debate",
  "'You caught the Suriel?' 'What like it's hard?'",
  "in a room where I can't even fuck you against the wall",
  "rereading ACOMAF for the 100th time",
  "being terrified of Nesta",
  "Lucien's brothers",
  "Feyre's scandalous dresses under the mountain",
  "Illyrian babies",
  "the metallic tang of magic",
  "Cassian's debilitating fear of Bryaxis",
  "using blood rubies as paper weights",
  "Cassian's fucked up childhood",
  "Rhysand's last name",
  "attempting to walk down 10,000 steps just to get wine",
  "watery bowels",
  "the Bogge",
  "'skewering' Miryam",
  "picturing the Bone Carver as your future child",
  "climbing 10,000 steps and then having enough energy to get it on with Cassian afterwards",
  "being forcefully turned into a firebird",
  "The Ouroboros Mirror",
  "having an illegitimate child with Helion",
  "being turned into 'ribbons'",
  "getting the ick from Feyre's cabin paintings",
  "the one bed trope",
  "Tamlin using their only chance of escape from Under the Mountain to grind on Feyre",
  "offering a 'kernel' of power",
  "receiving a head on a spike as a 'present'",
  "fairy wine",
  "luring the bogge to fuck with Dagdan and Brannagh",
  "fairy porn",
  "letting the water wraiths starve in poverty",
  "modern technology and weaponry would send the ACOTAR characters into a coma",
  "Sarah Janet Maas",
  "that time three rookies somehow managed to win the blood rite",
  "Kallias",
  "the huntress with an artist's soul",
  "using the word 'mate' one-hundred and eleven times in one book",
  "Balthazar",
  "destroying <em>only</em> one building in the Summer Court",
  "stealing sacred texts from the Summer Court",
  "hoarding baubles like a firedrake",
  "ordering the house to deny Nesta wine",
  "gardening duty with Elain",
  "having to kill two innocent fae in the third task",
  "'misting'",
  "clicking your tongue",
  "Drakon and Miryam",
  "The River House",
  "taunting Tamlin just enough to get him to blow up your paints",
  "faebane",
  "shipping Lucien and Azriel",
  "Nesta's character arc",
  "wedding for conquest",
  "Rhysand",
  "nearly letting Lanthys escape the prison",
  "Cassian's seasonal allergies",
  "avenging you sister Clythia",
  "covering yourself in wyrm shit",
  "Rhys's desperate need for a lint roller",
  "Cassian kissing Nesta despite the fact she's glowing with death in her eyes",
  "begrudgingly giving a 'kernal' of power to save Rhysand",
  "wings and embers",
  "The Dusk Court ???",
  "being banned from the Summer Court",
  "being able to see the future but letting yourself get kidnapped by Hybern",
  "the throne scene at the Court of Nightmares",
  "scrying",
  "the ACOTAR Christmas Special",
  "offering soup as a courtship ritual",
  "The Valkyrie",
  "Tamlin blatantly ignoring Feyre's letter and deciding to take her back anyways",
  "being able to see the future but conveniently showing up just moments after your dad gets his neck snapped",
  "The Court of Nightmares",
  "nearly killing Feyre just to see if she could get the ring or not",
  "Tarquin",
  "cursing the Spring Court for 49 years",
  "being Cauldron made",
  "the deleted threesome scene",
  "the Elriel stans",
  "an ever-growing list of book boyfriends",
  "throwing a bone at Amarantha",
  "getting stuck in a really unflattering mask for 49 years",
  "The Lord of Bloodshed",
  "teaching traumatized orphans how to paint",
  "Nyx",
  "befriending the Bone Carver",
  "soup",
  "Jurian the drama queen",
  "The Summer Court",
  "Nuala and Cerridwen",
  "being bitten by Tamlin",
  "that little sound she makes before she climaxes",
  "Devlon",
  "getting your nether regions covered in paint",
  "knowing Nesta is in trouble because you can smell her piss",
  "fleeing to Cretea with your seraphim lover",
  "Helion's pegasus",
  "nutting in your breeches",
  "pork and bean soup",
  "the ship wars",
  "knowing about lactic acid but not C-sections",
  "Tamlin's baldric",
  "stealing magic from the cauldron",
  "gifting a robe to the Suriel",
  "himbo energy",
  "Nesta needs a fitbit",
  "feeling an 'invisible talon-tipped hand' scrape against your brain",
  "Mind-Stilling",
  "pre-training porridge",
  "sending a message down the mating 'soul-bridge'",
  "your only options are a tunic or a ballgown",
  "Mor's questionable Solstice gifts",
  "keeping Illyrian wings as trophies",
  "Aunt Ripleigh",
  "partying the night away at Rita's",
  "making a deal with Bryaxis",
  "Rhysand always casually leaning against a wall",
  "roaring loud enough to bring down a mountain",
  "the pleasure barge",
  "wings and ruin",
  "eternally chasing that feeling you had reading ACOTAR for the first time",
  "the enigma known as 'the continent'",
  "making a dumb death pact with your mate",
  "those human queen bitches",
  "comparing a crackling fire to the sound of your dad's neck snapping",
  "showing up to save the Summer Court even though they hate you for stealing their book",
  "whispering to your shadows",
  "putting your hands on the headboard",
  "Briallyn",
  "naming your ships after your daughters",
  "convincing the Illyrians you're a witch",
  "Nesta saying 'fuck you' to Elain",
  "Varian",
  "bland human food",
  "the dreamer born into a court of nightmares",
  "the attack on Velaris",
  "'Stay with the High Lord'",
  "being gullible enough to get tricked at a masquerade ball hosted by Amarantha",
  "attacking Beron even though you said you'd remain calm",
  "your useless father",
  "releasing Amren's true form",
  "the naga",
  "Amren",
  "defending the Rainbow of Velaris",
  "'Rhysand is the most handsome High Lord'",
  "Nesta's rebellious phase",
  "Merrill",
  "Rhysand's purple eyes",
  "the book of breathings",
  "the inner circle",
  "leaking a tv show with a photo of a peanut butter and jelly sandwich",
  "the horrifying possibility that Tamlin is your dad",
  "nearly killing Lucien because you can't read",
  "not following a single piece of advice from Alis",
  "The Bone Carver",
  "a Nickelodeon style crossover book",
  "seducing your mate while he's in the sauna with his brothers",
  "licking Feyre's tears",
  "Rhys threatening to straight up kill Nesta",
  "Lanthys",
  "conveniently finding the mask just as you're about to drown in the Bog of Oorid",
  "sending dirty talk 'down the bond'",
  "inciting a war because the cauldron made you an ugly crone",
  "Illyrian leathers",
  "bargaining with the High Lord of the Night Court",
  "Azriel fixing Feyre and Cassian's sloppy drunken decorations",
  "Nesta's smutty books",
  "Mor's bizarre absence in ACOSF",
  "Illyrian bastard",
  "'Is this just the Hunger Games?'",
  "absolutely shattering Ianthe's hand",
  "Lucien's dead girlfriend, Jesminda",
  "twincest between Dagdan and Brannagh",
  "making your pelvis more pliant for Illyrian childbirth",
  "The Hybern Hologram",
  "Clotho",
  "Suriel Sex",
  "my concerning hyperfixation on anything related to ACOTAR",
  "the largest wingspan",
  "being forced to pick lentils out of a fireplace",
  "Mor and Emerie",
  "getting drunk and decorating with Cassian",
  "a roll in the hay with Isaac Hale",
  "Why is everyone wearing tunics?",
  "slamming into a pole because your mate sent you a sexy daydream",
  "being led on by Mor for centuries",
  "Under the Mountain",
  "pouring oil on your brother's hands and then lighting them on fire for funsies",
  "the puca",
  "confining Koschei to a lake",
  "The SJM Multiverse of Madness",
  "platonically gifting your friend a matching lingerie set for Solstice",
  "silver flames",
  "forcing Tamlin to bow before you",
  "Feyre's dead mom",
  "giving Cassian a blowjob at the dining room table",
  "Page 666",
  "being fooled into the thinking the fae can't lie",
  "Ramiel",
  "Thesan's lover",
  "being quick off the mark",
  "nearly dying in childbirth because you HAD to get it on with wings",
  "ignoring your fiance as she vomits in the middle of the night",
  "Clare Beddor's corpse",
  "getting tortured by Azriel",
  "Cassian and Nesta are the equivalent of Emmett and Rosalie from Twilight",
  "having a mental breakdown at the sight of red flower petals",
  "the shockingly polarizing events of Azriel's bonus chapter",
  "Feyre being a pinterest girl in her sweater and leggings",
  "humans deciding to live in squalor in Prythian instead of just going to the continent after the war",
  "enemies to lovers",
  "'Hard enough to make pictures fall off.'",
  "aerobics class with Cassian",
  "Feyre's deadbeat dad",
  "'His growls of pleasure filled the tent, drowning out distant cries of the injured and dying.'",
  "Azriel's headache medicine",
  "Amren's love of shiny objects",
  "The Bat Boys sledding down the stairs a la Princess Diaries 2",
  "The Rainbow of Velaris",
  "using Amren aka 'the firedrake' as a cautionary bedtime story",
  "Madja",
  "Amarantha",
  "The Day Court",
  "Mor is secretly a horse girl",
  "Lucien's personality in the first book compared to the remainder of the series",
  "death incarnate, night triumphant",
  "'Maybe you'll become interesting at last, Elain.'",
  "painting on the walls like a toddler",
  "an insatiable wing kink",
  "'Your hair is clean'",
  "Helion's sexual fantasies",
  "Rhysand's personal feast",
  "being a dick at the Tithe",
  "raising an army of the dead from the Bog of Oorid",
  "emptying your stomach onto the floor",
  "'lesser' fairies",
  "locking your traumatized fiance in your palace",
  "the 200th annual snowball fight",
  "having the smallest wingspan",
  "beheading Hybern",
  "a breeding kink",
  "growling",
  "nutting at the mental image of your unborn child",
  "painting eyeballs on a cabin that is not yours",
  "Elain",
  "Amren being forced to excrete waste",
  "vomiting into a potted plant",
  "Tamlin doing absolutely nothing to help Feyre under the mountain",
  "stealing magic from the high lords of Prythian",
  "The Autumn Court",
  "camping with Cassian",
  "Eris's hounds",
  "just straight up copying a map of the UK to create Prythian",
  "Rhys crashing the wedding",
  "mates being 'rare'",
  "peeing yourself in fear",
  "the Court of Dreams",
  "planting flowers instead of vegetables to feed your starving family",
  "the reminder that Rhys wears knee high boots",
  "not being able to solve the easiest riddle in history",
  "purring",
  "adding a chapter to the book about the Valkyrie",
  "Tampon",
  "trying to reclaim Feyre but also accidentally getting Feyre's sisters kidnapped and thrown in the cauldron",
  "Nephelle being an absolute badass",
  "the prince of merchants",
  "taking advantage of the residents displaced after the attack on Velaris and building a house on the land they fled",
  "dating someone 500 years older than you",
  "the mating bond",
  "chilling in the sauna with your bros",
  "bundle of nerves",
  "The Dawn Court",
  "killing the attor and then rarely doing anything that cool ever again in the rest of the series",
  "remembering halfway through that this is a Beauty and the Beast retelling",
  "the kelpie",
  "convincing everyone at Summer Solstice that you're the blessed one instead of Ianthe",
  "frost and starlight",
  "Winter Solstice",
  "gifting Azriel ear plugs to block out all of the Nessian sex",
];

export default whiteCardDeck;
